version: '3'
services:
  app:
    build: ./app
    links:
      - redis
    ports:
      - "5000:5000"
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  worker:
    build: ./app
    command: python worker.py runworker
    depends_on:
      - redis
